### ISSUE TITLE
Can't fire events from Laravel

### ISSUE THREAD

**Issue by goosechaser** [BrainBoxLabs/brain-socket#1]
Using your chat example and running `Event::fire('generic.event, [])` from within Laravel does not produce anything on the client side (i.e., no console message although there is a listener registered in JS). 

Chat works fine otherwise. Am I missing something?

P.S. I wish you guys used SockJS.

**Comment by chernandezq** [comment]
@BrainBoxLabs Finally, something to send notifications frontend development from Laravel

**Comment by jignesh87** [comment]
hii..any update for push..

**Comment by jignesh87** [comment]
From where following msg comes
"A message from a generic event fired in Laravel!"
any idea?

**Comment by jignesh87** [comment]
hello all ..
if i want dynamic data from server instead of message..
then what i have to do??

**Comment by jignesh87** [comment]
anybody has example of use of "Ratchet" except chat application.?
Thanks

**Comment by cjthomp** [comment]
No updates or activity in coming up on a year, I think it's safe to say this is abandoned.

**Comment by jignesh87** [comment]
Do you have any idea to achive server side functionality?
