### ISSUE TITLE
Brainsocket isnot working when I config site with https

### ISSUE THREAD

**Issue by tmbnh1** [BrainBoxLabs/brain-socket#12]
Hello,
I installed brainsocket and it's working. But after I change my site to https, brainsocket is stop working and I edit connect command: new WebSocket('wss://myip:8080'). It's not working too.

Please help me!
Thank you very much!

**Comment by wanmigs** [comment]
how could setup brainsocket over https site. brainsocket does not work even i changed ws to wss.

**Comment by maironsoft** [comment]
"The best solution is to put a SSL proxy (Nginx, STunnel, or HAProxy) in front of your WebSocket server to encrypt+decrypt your traffic." Does anyone know how I can do this?, Is there a tutorial?
