### ISSUE TITLE
Laravel Connection Refused in Homestead Vagrant Machine

### ISSUE THREAD

**Issue by joelcdoyle** [BrainBoxLabs/brain-socket#16]
Hey! I'm trying BrainSocket for the first time with Laravel 4.2, and I keep getting:

```
WebSocket network error: The operation couldn’t be completed. Connection refused
```

in the JS console in Safari.

I have followed directions, exactly, for the Laravel and JS sides. I'm using a Homestead Vagrant instance running on my local machine for development. I've tried starting the server with different ports: 8080, 8081, 8082. I've tried changing the URL to my project URL instead of localhost.

```
window.app = {};
app.BrainSocket = new BrainSocket(
        new WebSocket('ws://my.projectname:8081'),
        new BrainSocketPubSub()
);
```

Still no luck. Do you guys know what I'm doing wrong? My guess is that some port forwarding needs to happen on the Vagrant box, but I'm not sure how to change it. Anybody have experience with this?

**Comment by mogahead** [comment]
hi @joelcdoyle i face the same problem how do you forward the port 
the error appear in console is :
Failed to construct 'WebSocket': The URL 'ws://platform2:8000:8081' is invalid. 
as platform2 is the project name 
i ran the server from terminal at this port 8081 and it run no problem
plz support
