### ISSUE TITLE
 Call to undefined method BrainSocket\BrainSocket::message()

### ISSUE THREAD

**Issue by cskiwi** [BrainBoxLabs/brain-socket#17]
I'm using the latest version of laravel,

And when I want to send an event to my clients I get the following error:
`Call to undefined method BrainSocket\BrainSocket::message()`

any idea why? and how to fix it?

**Comment by rommmy** [comment]
same here, using l4.1 

Looking at the BrainSocket class, there is no message method at all anyway.

**Comment by rommmy** [comment]
My bad actually it's the BrainSocketAppResponse class being used. So basically to make it work you just need to turn the methods (message, success, error) as static.

**Comment by thepauleh** [comment]
just ignore your typehinting, it's just BrianSocket, not \Brainsocket\Brainsocket - some laravel thing
