### ISSUE TITLE
change requirements to  guzzle/guzzle

### ISSUE THREAD

**Issue by hrantly** [BrainBoxLabs/brain-socket#24]
d:\>composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Package guzzle/common is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/stream is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/parser is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/http is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Generating autoload files

**Comment by Sotiris-k** [comment]
Correct me if I'm wrong but those dependencies are ratchet's which brainsocket uses so there's nothing much they can do about it.
