### ISSUE TITLE
What are the event listeners for and why should I add filters.php?

### ISSUE THREAD

**Issue by Repox** [BrainBoxLabs/brain-socket#4]
A few questions I can't get answered by the README.

I fail to understand what the event listeners are for?

If I test a websocket message, like so:

```
<a href="javascript:app.BrainSocket.message('generic.event', {'message':'my message'});" class="btn btn-info btn-xs btn-block" role="button">Test</a>
```

All clients recieve the object perfectly well.
This without having the event listeners. Adding them, I see no difference - all clients still recieve the websocket messages.

And in addition to this, the event listeners are returning `BrainSocket::message()' - what data and where are they returning it to? Because the data isn't coming out to the clients?

I cannot see why I should add filters.php? I'm not adding or changing anything, so what am I missing?

Thank you.

**Comment by sudiptpa** [comment]
It is there any updates on PUSH notifications ..
